{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c4482c58-7f9e-4225-8a74-71458a0acfca",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\asus1\\AppData\\Local\\Temp\\ipykernel_18760\\1135070393.py:121: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)\n",
      "  label_result_class['text'] = f'CS Class = {int(cs_class[0])} (0=Low CS, 1=Normal CS, 2=High CS)'\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import messagebox, ttk\n",
    "from PIL import Image, ImageTk\n",
    "import numpy as np\n",
    "import joblib\n",
    "import os\n",
    "import sys\n",
    "from catboost import CatBoostClassifier, CatBoostRegressor  # Import CatBoost\n",
    "\n",
    "# Initialize the main window\n",
    "root = tk.Tk()\n",
    "root.title(\"GUI for Classifying and Predicting Concrete Compressive Strength\")\n",
    "\n",
    "# Create the main canvas\n",
    "canvas = tk.Canvas(root, width=1000, height=700, background='#FFFFFF')\n",
    "canvas.pack()\n",
    "\n",
    "# Load the image from the desktop and create an image on the canvas using PIL\n",
    "image_path = \"C:/Users/asus1/Desktop/image.jpg\"\n",
    "\n",
    "try:\n",
    "    image = Image.open(image_path)\n",
    "except FileNotFoundError:\n",
    "    messagebox.showerror(\"Error\", f\"The file at {image_path} was not found. Please check the path and try again.\")\n",
    "    root.quit()  # Gracefully exit the main loop\n",
    "    sys.exit()   # Exit the entire application\n",
    "\n",
    "# Scale the image to fit the canvas if needed\n",
    "image = image.resize((1000, 200), Image.LANCZOS)\n",
    "\n",
    "# Store the image in an attribute of root to prevent garbage collection\n",
    "root.image_storage = ImageTk.PhotoImage(image)\n",
    "canvas.create_image(500, 200, image=root.image_storage, anchor=\"center\")\n",
    "\n",
    "# Function to create labels on the canvas\n",
    "def create_label(text, font, fg, bg, x, y):\n",
    "    label = tk.Label(root, text=text, font=font, fg=fg, bg=bg)\n",
    "    canvas.create_window(x, y, anchor=\"w\", window=label)\n",
    "    return label\n",
    "\n",
    "# Define model paths for regression and classification\n",
    "regression_model_path = \"C:/Users/asus1/Desktop/catb_reg.joblib\"\n",
    "classification_model_path = \"C:/Users/asus1/Desktop/catb_class.joblib\"\n",
    "\n",
    "# Load the models\n",
    "if not os.path.exists(regression_model_path):\n",
    "    messagebox.showerror(\"Error\", \"Regression model file not found.\")\n",
    "    root.quit()  # Gracefully stop the app\n",
    "    sys.exit()   # Exit the entire application\n",
    "\n",
    "if not os.path.exists(classification_model_path):\n",
    "    messagebox.showerror(\"Error\", \"Classification model file not found.\")\n",
    "    root.quit()  # Gracefully stop the app\n",
    "    sys.exit()   # Exit the entire application\n",
    "\n",
    "regression_model = joblib.load(regression_model_path)\n",
    "classification_model = joblib.load(classification_model_path)\n",
    "\n",
    "# Define the GUI elements\n",
    "# Title split into two lines\n",
    "label_inputdefinetitle1 = create_label('GUI for Classifying and Predicting Concrete Compressive Strength', \n",
    "                                      ('Consolas', 18, 'bold', 'underline'), '#0000FF', '#FFFF00', 20, 30)\n",
    "label_inputdefinetitle3 = create_label('Developers: Mohamed K. Elshaarawy, Abdelrahman K. Hamed & Mostafa M. Alsaadawi', \n",
    "                                      ('Consolas', 16, 'bold'), '#C00000', '#FFFFFF', 20, 80)\n",
    "label_inputdefinetitle = create_label('Definition of Parameters', ('Consolas', 16, 'bold'), '#000000', '#FFFFFF', 50, 310)\n",
    "\n",
    "# Update parameter labels with kg/m³\n",
    "param_labels = [\n",
    "    'X1: Cement (kg/m³)',\n",
    "    'X2: Blast Furnace Slag (kg/m³)',\n",
    "    'X3: Fly Ash (kg/m³)',\n",
    "    'X4: Water (kg/m³)',\n",
    "    'X5: Superplasticizer (kg/m³)',\n",
    "    'X6: Coarse Aggregate (kg/m³)',\n",
    "    'X7: Fine Aggregate (kg/m³)',\n",
    "    'X8: Age (day)',\n",
    "]\n",
    "for i, text in enumerate(param_labels, start=1):\n",
    "    create_label(text, ('Consolas', 14, 'bold'), '#00008B', '#FFFFFF', 50, 320 + i * 30)\n",
    "\n",
    "label_inputs = create_label('Inputs', ('Consolas', 16, 'bold'), '#000000', '#FFFFFF', 620, 310)\n",
    "\n",
    "entry_fields = ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8']\n",
    "entries = {}\n",
    "for i, field in enumerate(entry_fields, start=1):\n",
    "    create_label(f'{field} = ', ('Consolas', 14, 'bold'), '#006600', '#FFFFFF', 550, 320 + i * 30)\n",
    "    entry = tk.Entry(root, font=('Consolas', 14, 'bold'), bg='#F0F0F0', highlightbackground='#000000', highlightthickness=1, bd=0, width=20)\n",
    "    canvas.create_window(750, 320 + i * 30, window=entry)\n",
    "    entries[field] = entry\n",
    "\n",
    "# Output labels for prediction and classification\n",
    "label_output = create_label('Output:', ('Consolas', 16, 'bold'), '#000000', '#FFFFFF', 50, 610)\n",
    "# Prediction labels are bold and underlined\n",
    "label_result_reg = create_label('CS Value (MPa):', ('Consolas', 14, 'bold', 'underline'), '#C00000', '#FFFFFF', 180, 610)\n",
    "label_result_class = create_label('CS Class:', ('Consolas', 14, 'bold', 'underline'), '#C00000', '#FFFFFF', 180, 640)\n",
    "\n",
    "# Function to predict and classify CS\n",
    "def predict():\n",
    "    # Collect input data\n",
    "    input_values = []\n",
    "    for field in entry_fields:\n",
    "        try:\n",
    "            value = float(entries[field].get())\n",
    "            if value < 0:\n",
    "                raise ValueError(\"Value must be non-negative.\")\n",
    "            input_values.append(value)\n",
    "        except ValueError as e:\n",
    "            messagebox.showerror(\"Error\", f\"Invalid input for {field}. Please enter a non-negative numeric value.\")\n",
    "            return\n",
    "\n",
    "    input_data = np.array([input_values])\n",
    "    \n",
    "    try:\n",
    "        # Predict CS value using regression model\n",
    "        cs_value = regression_model.predict(input_data)\n",
    "        # Classify CS using classification model\n",
    "        cs_class = classification_model.predict(input_data)\n",
    "        \n",
    "        # Update output labels with the prediction results\n",
    "        label_result_reg['text'] = f'CS Value = {cs_value[0]:.2f} MPa'\n",
    "        label_result_class['text'] = f'CS Class = {int(cs_class[0])} (0=Low CS, 1=Normal CS, 2=High CS)'\n",
    "    except Exception as e:\n",
    "        messagebox.showerror(\"Error\", f\"An error occurred during prediction: {e}\")\n",
    "\n",
    "# Predict button\n",
    "predict_button = tk.Button(root, text='Calculate', font=('Consolas', 16), command=predict, fg='#FFFFFF', bg='dark blue')\n",
    "canvas.create_window(750, 650, window=predict_button)\n",
    "\n",
    "# Run the main loop\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aefcf370-c651-4c8d-b288-072e3d7ab3fb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
